import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { baselightTheme } from "@/theme/DefaultColors";
import { ReduxProvider } from './redux/provider';
import Layout from './layout/Layout';
import "./globals.css";

export const metadata: Metadata = {
  title: "Amyr Smart Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeProvider theme={baselightTheme}>
            <CssBaseline />
            <Layout>
              {children}
            </Layout>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
